### ISSUE TITLE
Database GUI Installer

### ISSUE THREAD

**Issue by sgbaird** [ShuHuang/batterygui#1]
Is [_Database GUI Installer.exe_](https://figshare.com/articles/A_database_of_battery_materials_auto-generated_using_ChemDataExtractor/11888115/2?file=22789757) meant to be a standalone, "plug-and-play" installer, or do the instructions in the README file need to be followed before running the installer?

Tried installing using _Database GUI installer.exe_ (336.65 MB) via [figshare link](https://doi.org/10.6084/m9.figshare.11888115.v2), but saw this as soon as it installed:
![image](https://user-images.githubusercontent.com/45469701/94198617-c439b880-fe74-11ea-9055-7394a825672d.png)

Not a whole lot to go off of unfortunately.

**Comment by ShuHuang** [comment]
Hi, the error should be the system compatibility issue which will be solved soon. Currently you can use Python to run the GUI app following the instructions provided. Thanks!

**Comment by sgbaird** [comment]
Thanks!
