### ISSUE TITLE
Do you have the raw data available in e.g. `csv` format?

### ISSUE THREAD

**Issue by sgbaird** [ShuHuang/batterygui#10]
@ShuHuang,

Very nice work!

Not too familiar with SQL, and would be nice to access the full, extracted data. Is it available in CSV format?

Sterling

(@ancarnevali)

**Comment by ShuHuang** [comment]
@sgbaird

Thanks. We did have a database in CSV format, which is at Figshare (https://doi.org/10.6084/m9.figshare.11888115.v2)

Shu

**Comment by sgbaird** [comment]
Fantastic. Thank you!
