### ISSUE TITLE
Some questions about the db

### ISSUE THREAD

**Issue by ancarnevali** [ShuHuang/batterygui#11]
Hi! 
Just bumped into the .csv version of the DB linked in #10, and would like to ask a couple clarifications:
- I see that the type of data is classified as either CDE-extracted or calculated via data augmentation. Is there a way to tell whether the CDE values are experimentally observed or e.g. DFT predicted?
- What is the meaning of the Property "voltage"? Is it the average voltage of a material? Is it even possible to associate a precise definition?
- Is "Num_records" the number of times a certain value has been retrieved from the literature?
- How can one interpret the "Type" column values, if many tags are present?

Thank you!

**Comment by ShuHuang** [comment]
Hi,

- There isn't a way to classify experimentally or DFT data currently, but you can modify the original data extraction code and include the relevant context info.
- There isn't a precise definition of 'voltage' as well, as we tried to keep it as general as possible. But you can also change the specifier definition in the source code to get the relevant data.
- Yes, num_records is the number of times that has been retrieved from multiple papers.
- The type column only has anode, cathode or electrolyte. How can many tags be present?

Hope these help!
